version: '3'

services:
#  varnish:
#    image: varnish:stable
#    environment:
#      - VARNISH_VCL_CONF=/etc/varnish/default.vcl
#      - VARNISH_LISTEN_ADDRESS=127.0.0.1
#      - VARNISH_LISTEN_PORT=6081
#    volumes:
#      - ./varnish:/etc/varnish
#    ports:
#      - "6081"

  nginx:
    image: nginx:latest
#    depends_on:
#      - varnish
    volumes:
      - ./nginx:/etc/nginx
    ports:
      - "80"
