version: '3'

services:
  varnish:
    image: varnish:stable
    ports:
      - "80:6081"
    environment:
      - VARNISH_VCL_CONF=/etc/varnish/default.vcl
      - VARNISH_LISTEN_ADDRESS=127.0.0.1
      - VARNISH_LISTEN_PORT=6081
    volumes:
      - ./default.vcl:/etc/varnish/default.vcl:ro

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    depends_on:
      - varnish
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
